// * Subquery Design System:
export type SqTextTypes = 'large'
  | 'largeSemiBold'
  | 'body'
  | 'bodyMedium'
  | 'medium'
  | 'small'
  | 'extraSmall'

export type SqTitleTypes = 'h1'
  | 'h2'
  | 'h3'
  | 'h4'
  | 'h5'
  | 'h6'

export type SqColors = 'sq-gray-9'
  | 'sq-gray-8'
  | 'sq-gray-7'
  | 'sq-gray-6'
  | 'sq-gray-5'
  | 'sq-gray-4'
  | 'sq-gray-3'
  | 'sq-gray-2'
  | 'sq-gray-1'
  | 'sq-blue-1'
  | 'sq-blue-2'
  | 'sq-blue-3'
  | 'sq-blue-4'
  | 'sq-blue-5'
  | 'sq-blue-6'
  | 'sq-pink-1'
  | 'sq-pink-2'
  | 'sq-pink-3'
  | 'sq-pink-4'
  | 'sq-pink-5'
  | 'sq-pink-6'
  | 'sq-success'
  | 'warning'
  | 'sq-error'
  | 'sq-info'

export type SqBgColors = 'sq-success'
  | 'sq-warning'
  | 'sq-error'
  | 'sq-info'
  | 'sq-waiting'